****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
* Date:                 Tue Apr 25 16:59:01 CEST 2023
* Job name:             run_py_subp.sh
* Job id:               27323883
* User:                 namourou
* Account:              lsst
* Submit host:          cca004
* Partition:            htc
* Quality of service:   normal
* Nodelist:             ccwslurm0366
****************************************************************
DESC setup
GO1
Incorporation of magnitudes in AMICO catalog

Catalog loaded at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/raw_amico_cats/cosmoDC2_small_photoz_flexzboost_v1_iband/DETECTIONS_DERIVED/ and will be saved in /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_i/

processing 9425
Healpix list : [9425, 9169, 9298, 9426, 9554, 9681] 
Now merging all input healpix files
Done. 
Incorporation of magnitudes
33668 0.1
69107 0.2
139986 0.4
210865 0.6
281744 0.8
352623 1.0
  GALID     FIELD_PROB ASSOC_ID ...       mag_y        mt_id_final
---------- ----------- -------- ... ------------------ -----------
3188132590   0.5433649     1453 ...  24.67458872036988     1885250
3188132954  0.57183796     1453 ...  24.50006096643456     1885596
3188132957    0.530703     1453 ...  23.30832840989088     1885599
3188132993 0.118147105     1453 ... 21.035364370106347     1885627
3188132999  0.15296642     1453 ... 22.535326456747196     1885631
There are : 0 galaxies which are not found inside input catalog
Program ran in : 297.30361914634705
Done.
G02
Reading amico files before merging
Reading tile =  9425
Reading clusters at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/raw_amico_cats/cosmoDC2_small_photoz_flexzboost_v1_iband/map_detections_refined_noBuffer_all_noDoubles_handFix.fits 
Reading members at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_i/9425_map_associations_w_mag.fits 
Saving table at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_i/
Traceback (most recent call last):
  File "/pbs/home/n/namourou/test_jupyter/cluster_challenge/prepare_catalogs/read_amico_mb_subp.py", line 29, in <module>
    amico_cl_data = Table.read(cl_inpath)['ID', 'Xphys', 'Yphys', 'Zphys','LAMBSTAR', 'SN_NO_CLUSTER', 'SN', 'UID', 'TILE']  
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/io/registry/core.py", line 197, in read
    fileobj = ctx.__enter__()
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/raw_amico_cats/cosmoDC2_small_photoz_flexzboost_v1_iband/map_detections_refined_noBuffer_all_noDoubles_handFix.fits'
GO3
****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
Date: Tue Apr 25 17:04:07 CEST 2023
Job informations can be found using these commands:
Accounting:
sacct -j 27323883
Efficiency:
seff 27323883
****************************************************************
