****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
* Date:                 Tue Apr 25 16:59:01 CEST 2023
* Job name:             run_py_subp.sh
* Job id:               27323912
* User:                 namourou
* Account:              lsst
* Submit host:          cca004
* Partition:            htc
* Quality of service:   normal
* Nodelist:             ccwslurm0067
****************************************************************
DESC setup
GO1
Incorporation of magnitudes in AMICO catalog

Catalog loaded at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/raw_amico_cats/cosmoDC2_small_photoz_flexzboost_v1_iband/DETECTIONS_DERIVED/ and will be saved in /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_i/

processing 9810
Healpix list : [9810, 10066, 9554, 9681, 9682, 9811, 9937, 9938] 
Now merging all input healpix files
Done. 
Incorporation of magnitudes
33881 0.1
69546 0.2
140874 0.4
212202 0.6
283531 0.8
354859 1.0
  GALID    FIELD_PROB ASSOC_ID ...       mag_y        mt_id_final
---------- ---------- -------- ... ------------------ -----------
5750114351  0.9679795     1579 ...  21.68630924954711     3270763
5750192326  0.9109755     1579 ... 21.924355285723035     3314281
5750443928 0.91772676     2446 ... 22.864958304064203     3410532
5750444016 0.87559146     2446 ... 23.651211729537366     3410617
5750453613 0.95213073     1579 ... 24.355871756244454     3419861
There are : 0 galaxies which are not found inside input catalog
Program ran in : 325.7264771461487
Done.
G02
Reading amico files before merging
Reading tile =  9810
Reading clusters at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/raw_amico_cats/cosmoDC2_small_photoz_flexzboost_v1_iband/map_detections_refined_noBuffer_all_noDoubles_handFix.fits 
Reading members at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_i/9810_map_associations_w_mag.fits 
Saving table at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_i/
Traceback (most recent call last):
  File "/pbs/home/n/namourou/test_jupyter/cluster_challenge/prepare_catalogs/read_amico_mb_subp.py", line 29, in <module>
    amico_cl_data = Table.read(cl_inpath)['ID', 'Xphys', 'Yphys', 'Zphys','LAMBSTAR', 'SN_NO_CLUSTER', 'SN', 'UID', 'TILE']  
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/io/registry/core.py", line 197, in read
    fileobj = ctx.__enter__()
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/raw_amico_cats/cosmoDC2_small_photoz_flexzboost_v1_iband/map_detections_refined_noBuffer_all_noDoubles_handFix.fits'
GO3
****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
Date: Tue Apr 25 17:04:38 CEST 2023
Job informations can be found using these commands:
Accounting:
sacct -j 27323912
Efficiency:
seff 27323912
****************************************************************
